dist: trusty
sudo: false
group: beta
language: node_js
node_js:
  - "7"
cache: yarn
install:
  - openssl ecparam -genkey -name secp521r1 -noout -out ec512.prv.pem
  - openssl ec -in ec512.prv.pem -pubout > ec512.pub.pem
  - yarn
script:
  - yarn test
  - yarn run -- codecov
  - yarn lint
