-- Up
CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY ASC,
    email TEXT UNIQUE NOT NULL,
    newEmail TEXT UNIQUE,
    emailToken TEXT,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    lastUsed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    kdfSalt BLOB NOT NULL,
    srpSalt BLOB NOT NULL,
    srpVerifier BLOB NOT NULL,
    timeBasedOneTimeSecret BLOB NOT NULL
);

-- Down
DROP TABLE Users;